import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topmenu from "@/components/TopMenu";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session=await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxProvider> */}
          <NextAuthProvider session={session}>
            <Topmenu/>
            {children}
          </NextAuthProvider>
        {/* </ReduxProvider> */}
        </body>
    </html>
  );
}
